### ISSUE TITLE
How to generate the data set for sliency map in this paper？

### ISSUE THREAD

**Issue by Banshenggua** [avakanski/Attention-Enriched-Deep-Learning-Model-for-Breast-Tumor-Segmentation#1]

**Comment by avakanski** [comment]
Calculating the saliency maps for the images is based on previous research work by the co-author Dr. Xian. I will check with him if he would be willing to share the codes for the saliency maps and I will get back to you soon. Alex

**Comment by Banshenggua** [comment]
·

**Comment by Banshenggua** [comment]
Thank you for your reply and your doing. I am being waiting in hope for the code.Thank you again!

**Comment by avakanski** [comment]
I talked to the co-author, and it was suggested that you contact another of the authors of the saliency maps approach - Dr. Fei Xu at <fei.xu at aggiemail.usu.edu>. I believe that Dr. Xu will be willing to share the codes.  Alex
