### ISSUE TITLE
UNet

### ISSUE THREAD

**Issue by He9702** [avakanski/Attention-Enriched-Deep-Learning-Model-for-Breast-Tumor-Segmentation#2]
Your research ideas and thesis are of great help to me. I see that your U_net network architecture is 32-32-64-64-128-64-63-32-32. Why is it not the original version? I try to go Change your web framework but there is a problem, can you help me ？
![image](https://user-images.githubusercontent.com/71333170/112127199-23983b80-8c00-11eb-83eb-9b96d869f062.png)

**Comment by avakanski** [comment]
Hi, we used a small size dataset and we found that a smaller model with a lower number of parameters compared to the original U-Net produced better results. If you work with larger size datasets, it is likely that the original U-Net architecture will outperform. Or, you can also try a few different architectures with different number of hidden units and/or layers, and check which one outputs the best results. 
Regarding your error, it looks that the predictions if your test set are all 0s or 1s, and AUC-ROC raises an error. I suggest to examine the outputs of your model first to understand the reason for the error, and I also noticed many suggestions on the web, e.g., increase the batch size, use StratifiedKFold, shuffle the data, etc. Try a few of these strategies and see if one will work. Link: https://stackoverflow.com/questions/45139163/roc-auc-score-only-one-class-present-in-y-true
Good luck, Alex

**Comment by He9702** [comment]
Thank you for your explanation, I understand.The advice given to my problem is very helpful to me, I already know what my problem is, thank you very much .
| |
贺琪琪
|
|
***@***.***
|
签名由网易邮箱大师定制
On 3/23/2021 ***@***.***> wrote：

Hi, we used a small size dataset and we found that a smaller model with a lower number of parameters compared to the original U-Net produced better results. If you work with larger size datasets, it is likely that the original U-Net architecture will outperform. Or, you can also try a few different architectures with different number of hidden units and/or layers, and check which one outputs the best results.
Regarding your error, it looks that the predictions if your test set are all 0s or 1s, and AUC-ROC raises an error. I suggest to examine the outputs of your model first to understand the reason for the error, and I also noticed many suggestions on the web, e.g., increase the batch size, use StratifiedKFold, shuffle the data, etc. Try a few of these strategies and see if one will work. Link: https://stackoverflow.com/questions/45139163/roc-auc-score-only-one-class-present-in-y-true
Good luck, Alex

**Comment by avakanski** [comment]
That is excellent, I am glad to hear that you have resolved the problem.
